name: Champ AI Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run AI Code Review
        uses: champ96k/ai-code-review-action@v1.2
        with:
          github_token: ${{ secrets.TOKEN }}
          google_api_key: ${{ secrets.GEMINI_API_KEY }}
